GUI = 600
NUM_CELLS = 60
CELL_W = int(GUI / NUM_CELLS)
START_X = 0  # GUI / 2
START_Y = 0  # GUI / 2
FPS = 15

NUM_POP = 80
NUM_GEN = 10000
PYGAME_LOOK_AFTER_GEN = 10
NUM_ELITES = 20
NUM_MUTATIONS = 10
NUM_OFFSPRING = 60

assert NUM_POP == NUM_ELITES + NUM_OFFSPRING
assert NUM_MUTATIONS <= NUM_POP